id: P004580
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 11:42:40.099053
source_metadata:
  id: bdr:W8LS16964
  title: བདེ་ཆེན་དགོན་གྱི་ཆོས་སྤྱོད།
  author: ''
  volumes:
    6c9e7ff1949645a88c960312d3f8c856:
      image_group_id: I8LS17025
      title: ''
      volume_number: 1
      total_pages: 1778
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
